### ISSUE TITLE
Vaccinations

### ISSUE THREAD

**Issue by MarceColl** [jeiros/JobSumitter#1]
How can this library help me not vaccinate my kid? The goverment doesn't allow my kid to go to school beacuse he is not vaccinated. But I don't want my kid to get autism. I see that you're an MD, help me please sir Run.

**Comment by jeiros** [comment]
Dunno bout that my man but reading the source code can sure give you autism

**Comment by MarceColl** [comment]
Do you think that if he reads just a function he may become immune to autism then? I'm fallbacking hard on that
